fix: Multi tenancy enabled bots need tenant passed
weaviate/weaviate-python-client pull request #1107
Opened 2024-06-12 21:10 UTC by sirjan-ws-ext

2024-06-13 13:44 UTC, dirkkul requested changes
thanks a lot for the bug fix!

Could you:
- make stable/v3 the target of your PR? Then we can release a new v3 version and merget it into main afterwards
- add a test to show the behaviour? There are a couple of tests in mock_tests/test_automatic_retries.py - you could copy an existing test and add a tenant check into the mock. If this is too much, just let me know

2024-06-13 13:44 UTC, dirkkul commented on weaviate/batch/crud_batch.py
> +                )
could you just make params conditional?

eg
```
tenant = obj.get("tenant", None)
params = {"tenant": tenant} id tenant is not None else None
response_head = self._connection.head(
     path="/objects/" + class_name + "/" + uuid,
     params=params,
)
```

and then the same for the get request below (just reuse params)

2024-06-13 13:50 UTC, sirjan-ws-ext commented on weaviate/batch/crud_batch.py
> +            obj_weav = response.json()
Ah, I had copied the code from 3.23 that I was using earlier, will update

2024-06-13 14:00 UTC, sirjan-ws-ext commented
Hi @dirkkul ,
The target is already `stable/v3`, am I missing something?
<img width="786" alt="Screenshot 2024-06-13 at 7 30 31 PM" src="https://github.com/weaviate/weaviate-python-client/assets/151817113/335cc8d7-f691-4e5a-b02e-fe30e2254b0c">

2024-06-13 14:42 UTC, dirkkul commented
> The target is already stable/v3, am I missing something?

whoops, must have mixed it up - all good there then :)

Are the tests clear? Or should I add a bit more context? I can also try to do it, but would only have time next week

2024-06-13 14:44 UTC, sirjan-ws-ext commented
> > The target is already stable/v3, am I missing something?
> 
> whoops, must have mixed it up - all good there then :)
> 
> Are the tests clear? Or should I add a bit more context? I can also try to do it, but would only have time next week

Thanks, I'll look into the tests in a couple of hours and get back. Shouldnt be an issue

2024-06-24 11:37 UTC, dirkkul commented
Hey @sirjan-ws-ext I added the tests [here](https://github.com/weaviate/weaviate-python-client/pull/1122), will close this PR in favour of the new one. Your commits will stay like they are so you get the credits for the fix :)

2024-06-24 11:37 UTC, closed without merging

2024-06-24 13:37 UTC, sirjan-ws-ext commented
Thanks for the help @dirkkul . Really appreciate it 💯