Added method to check if a class exists
weaviate/weaviate-python-client pull request #300
Opened 2023-04-22 14:22 UTC by meetagrawal09

This PR fixes #232.

2023-04-23 03:37 UTC, meetagrawal09 commented
> To avoid any confusion in the future about your contribution to Weaviate, we work with a [Contributor License Agreement](https://weaviate.io/service/contributor-license-agreement). If you agree, you can simply add a comment to this PR that you agree with the CLA so that we can merge.beep boop - the Weaviate bot 👋🤖PS:Are you already a member of the [Weaviate Slack channel?](https://weaviate.io/slack)

I agree with the Contributor License Agreement.

2023-04-25 06:03 UTC, dirkkul requested changes

2023-04-25 06:03 UTC, dirkkul commented on integration/test_schema.py
> +    assert not class_does_not_exist
Would you create an extra test for this?

I'd rather not mix different things. Also please assert directly eg
```
assert client.schema.exists("Barbecue")
assert not client.schema.exists("Not-Barbecue")
```

2023-04-25 06:03 UTC, dirkkul commented on weaviate/schema/crud_schema.py
> +        return len(schema["classes"]) > 0
this doesn't work as you already got the specific class, eg the return is not the complete schema

2023-05-04 10:17 UTC, StefanBogdan commented
Since this was a priority we added this feature already, closing.

2023-05-04 10:17 UTC, closed without merging

2023-05-04 10:21 UTC, hsm207 commented
@StefanBogdan which PR implemented this feature?

2023-05-04 10:50 UTC, StefanBogdan commented
@hsm207 this one: https://github.com/weaviate/weaviate-python-client/pull/311