allow skip and vectorizePropertyName be optional
weaviate/weaviate-python-client pull request #888
Opened 2024-02-19 21:42 UTC by dudanogueira

In some modules, like `multi2vec_bind`, skip and vectorizePropertyName may not be present on the response for the schema.

This is the output of the created schema below:

```
{
   "class":"Animals",
   "invertedIndexConfig":{
      "bm25":{
         "b":0.75,
         "k1":1.2
      },
      "cleanupIntervalSeconds":60,
      "stopwords":{
         "additions":null,
         "preset":"en",
         "removals":null
      }
   },
   "moduleConfig":{
      "multi2vec-bind":{
         "audioFields":[
            "audio"
         ],
         "imageFields":[
            "image"
         ],
         "vectorizeClassName":true,
         "videoFields":[
            "video"
         ]
      }
   },
   "multiTenancyConfig":{
      "enabled":false
   },
   "properties":[
      {
         "dataType":[
            "text"
         ],
         "description":"This property was generated by Weaviate's auto-schema feature on Mon Feb 19 21:26:04 2024",
         "indexFilterable":true,
         "indexSearchable":true,
         "moduleConfig":{
            "multi2vec-bind":{
               
            }
         },
         "name":"name",
         "tokenization":"word"
      },
      {
         "dataType":[
            "text"
         ],
         "description":"This property was generated by Weaviate's auto-schema feature on Mon Feb 19 21:26:04 2024",
         "indexFilterable":true,
         "indexSearchable":true,
         "moduleConfig":{
            "multi2vec-bind":{
               
            }
         },
         "name":"path",
         "tokenization":"word"
      },
      {
         "dataType":[
            "text"
         ],
         "description":"This property was generated by Weaviate's auto-schema feature on Mon Feb 19 21:26:04 2024",
         "indexFilterable":true,
         "indexSearchable":true,
         "moduleConfig":{
            "multi2vec-bind":{
               
            }
         },
         "name":"image",
         "tokenization":"word"
      },
      {
         "dataType":[
            "text"
         ],
         "description":"This property was generated by Weaviate's auto-schema feature on Mon Feb 19 21:26:04 2024",
         "indexFilterable":true,
         "indexSearchable":true,
         "moduleConfig":{
            "multi2vec-bind":{
               
            }
         },
         "name":"mediaType",
         "tokenization":"word"
      }
   ],
   "replicationConfig":{
      "factor":1
   },
   "shardingConfig":{
      "virtualPerPhysical":128,
      "desiredCount":1,
      "actualCount":1,
      "desiredVirtualCount":128,
      "actualVirtualCount":128,
      "key":"_id",
      "strategy":"hash",
      "function":"murmur3"
   },
   "vectorIndexConfig":{
      "skip":false,
      "cleanupIntervalSeconds":300,
      "maxConnections":64,
      "efConstruction":128,
      "ef":-1,
      "dynamicEfMin":100,
      "dynamicEfMax":500,
      "dynamicEfFactor":8,
      "vectorCacheMaxObjects":1000000000000,
      "flatSearchCutoff":40000,
      "distance":"cosine",
      "pq":{
         "enabled":false,
         "bitCompression":false,
         "segments":0,
         "centroids":256,
         "trainingLimit":100000,
         "encoder":{
            "type":"kmeans",
            "distribution":"log-normal"
         }
      }
   },
   "vectorIndexType":"hnsw",
   "vectorizer":"multi2vec-bind"
}
```

How to reproduce:

```python
import weaviate
client = weaviate.connect_to_local()

from weaviate import classes as wvc
client.collections.delete("Test")
c = client.collections.create(
    "Test",
    vectorizer_config=wvc.config.Configure.Vectorizer.multi2vec_bind(
        text_fields=["text"],
    )
)
# work here
c.config.get()

c.data.insert({"text": "text"})

# not anymore
c.config.get()

# ERROR: KeyError: 'skip'
```

2024-02-20 02:01 UTC, dirkkul reviewed
Thanks for the PR! :) Would you be able to add a test? A mock is also fine (ping me on slack if anything is unclear)

2024-02-21 10:11 UTC, tsmith023 requested changes

2024-02-21 10:11 UTC, tsmith023 commented on weaviate/collections/classes/config_methods.py
> +                    ),
Since `skip` and `vectorize_property_name` are `bool`, can the default return here be `False` rather than `None`?

2024-02-22 05:36 UTC, dirkkul commented
I added a test here and merged including your commits :)

 https://github.com/weaviate/weaviate-python-client/pull/906

2024-02-22 05:36 UTC, closed without merging